### ISSUE TITLE
[BUG] `java.lang.NoSuchFieldException: b`

### ISSUE THREAD

**Issue by Evil0ctal** [PedroJM96/CoreLibBukkit#3]
Server version: 1.20.1 PaperMC
plugin version: 4.6.2
```
[15:31:22 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
[15:31:22 WARN]: java.lang.NoSuchFieldException: b
[15:31:22 WARN]:        at java.base/java.lang.Class.getField(Class.java:2117)
[15:31:22 WARN]:        at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
[15:31:22 WARN]:        at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
[15:31:22 WARN]:        at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
[15:31:22 WARN]:        at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
[15:31:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:31:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:31:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[15:31:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[15:31:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[15:31:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[15:31:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:31:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Evil0ctal** [comment]
Same issue:

https://github.com/PedroJM96/CoreLibBukkit/issues/2

**Comment by PedroJM96** [comment]
Fixed in the next version
