### ISSUE TITLE
Spam in console Spigot 1.20.1

### ISSUE THREAD

**Issue by eZomb** [PedroJM96/CoreLibBukkit#4]
Idk if this is bug/error but i want to publish it to help the plugin

**Comment by eZomb** [comment]
[10:47:32] [Server thread/WARN]: java.lang.NoSuchFieldException: b
[10:47:32] [Server thread/WARN]:        at java.base/java.lang.Class.getField(Class.java:2117)
[10:47:32] [Server thread/WARN]:        at com.pedrojm96.pixellogin.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
[10:47:32] [Server thread/WARN]:        at com.pedrojm96.pixellogin.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
[10:47:32] [Server thread/WARN]:        at com.pedrojm96.pixellogin.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
[10:47:32] [Server thread/WARN]:        at com.pedrojm96.pixellogin.bukkit.ChannelController$1$1.run(ChannelController.java:129)
[10:47:32] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82)
[10:47:32] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[10:47:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257)
[10:47:32] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[10:47:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198)
[10:47:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015)
[10:47:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[10:47:32] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by PedroJM96** [comment]
Fixed in the next version
