### ISSUE TITLE
got loop error while joining server

### ISSUE THREAD

**Issue by brokenedtzjs** [PedroJM96/CoreLibBukkit#6]
installed latest version plugins **4.6.9** on spigotmc and got loop error while joining the server until im disconnected

logs:
```cmd
server_1  | [04:23:15 INFO]: UUID of player BrokenEdtz is ...
server_1  | [04:23:15 INFO]: BrokenEdtz joined the game
server_1  | [04:23:15 INFO]: BrokenEdtz[/...] logged in with entity id 320 at ([world]0.5, 88.0, -8.5)
server_1  | [04:23:15 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:15 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:15 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:15 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:15 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:15 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:15 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:15 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:15 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:15 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:15 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:15 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:15 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:15 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:15 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:16 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:16 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:16 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:16 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:16 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:16 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:16 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:16 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:16 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:16 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:16 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:16 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:16 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:16 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:16 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:17 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:17 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:17 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:17 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:17 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:17 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:17 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:17 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:17 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:17 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:17 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:17 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:17 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:17 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:17 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:18 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:18 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:18 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:18 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:18 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:18 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:18 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:18 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:18 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:18 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:18 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:18 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:18 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:18 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:18 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:19 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:19 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:19 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:19 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:19 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:19 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:19 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:19 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:19 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:19 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:19 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:19 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:19 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:19 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:19 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:20 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:20 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:20 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:20 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:20 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:20 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:20 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:20 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:20 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:20 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:20 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:20 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:20 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:20 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:20 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:21 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:21 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:21 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:21 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:21 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:21 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:21 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:21 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:21 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:21 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:21 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:21 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:21 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:21 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:21 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:22 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:22 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:22 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:22 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:22 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:22 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:22 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:22 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:22 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:22 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:22 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:22 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:22 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:22 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:22 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:23 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:23 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:23 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:23 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:23 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:23 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:23 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:23 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:23 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:23 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:23 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:23 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:23 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:23 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:23 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:24 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:24 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:24 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:24 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:24 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:24 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:24 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:24 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:24 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:24 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:24 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:24 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:24 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:24 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:24 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:28 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:28 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:28 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:28 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:28 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:28 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:28 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:28 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:28 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:28 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:28 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:28 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:28 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:28 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:28 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:29 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:29 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:29 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:29 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:29 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:29 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:29 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:29 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:29 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:29 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:29 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:29 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:29 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:29 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:29 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:30 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:30 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:30 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:30 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:30 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:30 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:30 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:30 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:30 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:30 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:30 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:30 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:30 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:30 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:30 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:43 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:43 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:43 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:43 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:43 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:43 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:43 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:43 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:43 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:43 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:43 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:43 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:43 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:43 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:43 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:44 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:44 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:44 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:44 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:44 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:44 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:44 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:44 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:44 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:44 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:44 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:44 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:44 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:44 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:44 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:45 INFO]: [STDOUT] [com.pedrojm96.superlobby.CoreReflection] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
server_1  | [04:23:45 WARN]: java.lang.NoSuchFieldException: b
server_1  | [04:23:45 WARN]:    at java.base/java.lang.Class.getField(Unknown Source)
server_1  | [04:23:45 WARN]:    at com.pedrojm96.superlobby.CoreReflection.sendPacketPos_1_19(CoreReflection.java:137)
server_1  | [04:23:45 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendPos_1_19_2(CoreActionBar.java:135)
server_1  | [04:23:45 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar.sendActionBar(CoreActionBar.java:86)
server_1  | [04:23:45 WARN]:    at com.pedrojm96.superlobby.effect.CoreActionBar$SendRun.run(CoreActionBar.java:45)
server_1  | [04:23:45 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
server_1  | [04:23:45 WARN]:    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
server_1  | [04:23:45 WARN]:    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
server_1  | [04:23:45 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
server_1  | [04:23:45 WARN]:    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
server_1  | [04:23:45 WARN]:    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
server_1  | [04:23:45 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
server_1  | [04:23:45 WARN]:    at java.base/java.lang.Thread.run(Unknown Source)
server_1  | [04:23:46 INFO]: BrokenEdtz lost connection: Disconnected
server_1  | [04:23:46 INFO]: [voicechat] Disconnecting client BrokenEdtz
server_1  | [04:23:46 INFO]: BrokenEdtz left the game
```

**Comment by brokenedtzjs** [comment]
**Fixed**
error shows while joined up than based server versions
based version: 1.20.1
joined using version: 1.20.2

fixed then using same version in based server version
maybe the issues is SuperLobby send Packet "c", but in CoreReflection.java detected "b"
